services:

  app1:
    build: ./backend-v1
    container_name: backend-v1

  app2:
    build: ./backend-v2
    container_name: backend-v2

  app3:
    build: ./backend-v3
    container_name: backend-v3

  proxy:
    build: ./proxy
    container_name: nginx-proxy
    ports:
      - "8080:80"
